import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import GithubButton from "../components/GithubButton";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <GithubButton />
          <p>
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nulla et
            aut cupiditate voluptas laboriosam aliquam! Delectus suscipit odit
            voluptas, fuga totam iusto ducimus dolorum labore, dicta quam
            aliquam dolores sunt!
          </p>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
